service: myki-api

provider:
  name: aws
  project: myki-api
  region: ap-southeast-2
  runtime: nodejs8.10
  stage: dev
  memorySize: 2048
  timeout: 30

functions:
  getBalance:
    handler: handler.getBalance
    events:
        - http: 
            path: myki/balance
            method: post

